id: P2E4DE3B8
initial_creation_type: input
source_metadata:
  title: Pilgrimage Series
  language: zh
  description: 'Lotsawa House presents the following texts related to pilgrimage (gnas
    skor) and major sacred places (gnas):'
  volume:
    0e8d24937c74499cb193b84850a5468c:
      title: The Three Types of Pilgrim
      parent: General
    f76cfef0d66d443d82b7ab6dd061980b:
      title: A Guide to Uḍḍiyāna (Ujjain), Benglor
      parent: Sacred Places
    655d6f92adb44deb89a80ae168f8bf6b:
      title: 'Melodious Tambura of Delight: A Guide to Māratika Cave, Supreme Site
        of Immortality'
      parent: Sacred Places
    a5167f39f4e7472184b64e1a0f555e91:
      title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress
        of the Jarung Kashor Stūpa
      parent: Sacred Places
    dffc3a0c5a31463b9b61b321d4d01f91:
      title: Prayer to the Three Great Stūpas of Kathmandu
      parent: Sacred Places
    0822e79229504362bdb12c3170856041:
      title: A Prayer to the Stūpa of Jarung Khashor in Boudha
      parent: Sacred Places
    6cea2f3ab6464ff2ad1dec0b24c5248a:
      title: A Prayer to the Svayambhū Stūpa in Nepal
      parent: Sacred Places
    8a4bbc1db07d4e84b7f9d86df6c0be3c:
      title: A Prayer to the Three Stūpas of Nepal
      parent: Sacred Places
    9cfe1e7cb71649be96a7faaf35cd99d6:
      title: A Short Guide to Yangleshö in Nepal
      parent: Sacred Places
    439ccde66c6244d2b2a1f9873eb1b981:
      title: 'A Song of Perfect Joy: In Praise of the Sacred Sites of Rājgṛha, Vulture
        Peak and Nālandā'
      parent: Sacred Places
    f70f7eeb9dbe4a3d88249325f7109db8:
      title: 'Gathering Auspiciousness: A Prayer of Aspiration Made in the Presence
        of the Sacred Mahābodhi Temple and its Imagery, Magadha, Land of the Āryas'
      parent: Sacred Places
    e9412cf65ff74accb84a75ae00995f09:
      title: Guide to Sengchen Namdrak
      parent: Sacred Places
    8bc8af83f66443ee9134219aac4da032:
      title: In Praise of Devāvatāra, Site of Buddha's Descent from Heaven
      parent: Sacred Places
    b5ef0a76175b447da288ef331ed93a96:
      title: In Praise of Kuśinagara
      parent: Sacred Places
    196fa00ef1f74d5b9bad2f6f17fb0ad0:
      title: In Praise of Vārāṇasī, the Supreme Place
      parent: Sacred Places
    2b42540bcbec4ca7b577f18d42b176f2:
      title: In Praise of Yangleshö in Nepal
      parent: Sacred Places
    343f935809614fe082ccce1cf68cbeaf:
      title: In Praise of the Great Indian City of Kolkata
      parent: Sacred Places
    f4f27f04597240bc8bc9fabb656b05bc:
      title: Offering Clouds to Delight the Victorious Ones, Combining A Praise of
        Redreng with a Prayer of Aspiration
      parent: Sacred Places
    f6f91477bf1b40be81b3164c74515dcf:
      title: Praise and Prayer to Kharchu, Great Sacred Place of Lhodrak
      parent: Sacred Places
    eec4394f2eaf4bd28c4565f286036eaf:
      title: Prayer of Aspiration to the Stūpa Commemorating the Bodily Sacrifice
        to the Tigress
      parent: Sacred Places
    718b6fdde3734884b4708ee95ae1c411:
      title: 'The Conquerors'' Delight: In Praise of Śrāvastī'
      parent: Sacred Places
    6ea627867fda439f85fe6f6139d22f79:
      title: 'The White Lotus Garland of Immortality: In Praise of the Supreme Vajra
        Place, Tso Pema (Lotus Lake)'
      parent: Sacred Places
    9bbccf19b24c4535af67f67f6fb0ca9e:
      title: 'The White Lotus: In Praise of Lumbinī'
      parent: Sacred Places
    f842cc640413413ea3210a4c44b761b0:
      title: The Guidebook to the Hidden Land of Pemokö
      parent: Sacred Places
    337f88a4805046b4b6549998c8fc2d55:
      title: A Prayer to Jowo Rinpoche Combined with Aspirations and a Means to Receive
        the Four Empowerments
      parent: Sacred Places
    ebfa4eeefec54720be3e1e8e30fb2d3c:
      title: 'The Kalaviṅka’s Call: A Guide to Glorious Samye Chimphu'
      parent: Sacred Places
    4c50938d349d42159196679ca8799a84:
      title: Upon Arriving at Yangleshö
      parent: Sacred Places
    c4dcbb88bb194850a6f771df8d537f76:
      title: An Aspiration to Travel to the Hidden Land of Pemokö
      parent: Sacred Places
    469e1effccb24873a9587e3b11b95299:
      title: Jangphen Namkha Dzong
      parent: Sacred Places
    3931867367ff42158c405742378c039e:
      title: 'Liberation Upon Hearing: The History of the Great Jarung Kashor Stūpa'
      parent: Sacred Places
    5c47b65fd77b417fa6d620aef2a1775b:
      title: 'Melodious Sound: In Praise of Vulture Peak Mountain'
      parent: Sacred Places
    75cd00584b7a4a8b87944d51b8873a4b:
      title: In Praise of the Hidden Valley of Kyimolung
      parent: Sacred Places
    47a18a75440f473091cef900c844d157:
      title: 'Auspicious Dance of Longevity: A Song for Touring the Sacred Sites of
        Nepal'
      parent: Songs
created_at: '2022-03-01T05:06:14.968161'
last_modified_at: '2022-03-01T05:06:14.968164'
